### ISSUE TITLE
ModuleNotFoundError: No module named 'websockets'

### ISSUE THREAD

**Issue by thislooksfun** [jvilk/mitmproxy-node#1]
Hello,

When I'm calling `MITMProxy.Create`, I keep getting the error `ModuleNotFoundError: No module named 'websockets'` at `mitmproxy/scripts/proxy.py`, line 15.

Do you have any idea what is causing this and how to fix it?

Thanks,
-tlf

**Comment by jvilk** [comment]
Yeah! mitmproxy-node's plugin for mitmproxy requires the Python websockets package. `npm install` should have taken care of that for you with its [postinstall step](https://github.com/jvilk/mitmproxy-node/blob/master/package.json#L10), which runs this script:

https://github.com/jvilk/mitmproxy-node/blob/master/scripts/install_python_deps.py#L21

The script should have failed with a descriptive error message if your system doesn't have the correct version of Python, failed to install websockets, etc.

Some possibilities:

* You didn't run `npm install`, so websockets was never installed.
* You ran `npm install`, but `websockets` was installed to a different version of Python than MITMProxy is invoking.
* You ran `npm install`, but maybe some error happened and you didn't notice, or was swallowed incorrectly by my script.

I suspect the second option to be most likely.

Does manually running the `install_python_deps.py` script fix your problem? (Run it from mitmproxy-node's root directory, e.g. where its `package.json` is.)

**Comment by thislooksfun** [comment]
Thanks for the prompt reply!

Running `install_python_deps.py` manually tells me
```
Requirement already satisfied: websockets==4.0.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r requirements.txt (line
1))
```
The issue is when I put in
```
import sys
raise Exception(sys.path)  # since print() is captured
```
`/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages` is not on the path. Instead, it's using '/usr/local/Cellar/mitmproxy/3.0.3_2/libexec/lib/python3.6/si
te-packages'.

Any ideas on how to make it behave?

**Comment by jvilk** [comment]
@thislooksfun Huh, odd. It looks like the current version of MITMProxy bundles its own version of Python?

btw, few things:

* You need to use MITMProxy v2. I haven't updated the library yet for v3, and know that it doesn't work with v3. (V3 was released very recently.)
* After uninstalling mitmproxy (which looks like you installed w/ brew?), you can install it directly via pip:

```
# or pip, depending on your setup :)
pip3 install mitmproxy==2.0.2
```

I believe installing w/ pip may require a few additional build dependencies. Let me know if you have trouble.

**Comment by thislooksfun** [comment]
That worked perfectly, thank you!
